spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/hsc-wechat-common
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 50
  redis:
    host: localhost
    password:
    port: 6379