spring:
  datasource:
    url: jdbc:mysql://localhost:5432/demo
    username: admin
    password: admin
    driver-class-name: org.gjt.mm.mysql.Driver
    hikari:
      maximum-pool-size: 50
  redis:
    host: localhost
    password:
    port: 6379